### ISSUE TITLE
Lower encoder resolution

### ISSUE THREAD

**Issue by ksstms** [legokor/TanfolyamRobot#18]
It should be okay to lower the encoder resolution from 4X to 1X in order to save CPU time on interrupt handling.

If we can believe this line, we get 12000 counts per second at full speed, which is a lot.
https://github.com/legokor/TanfolyamRobot/blob/a2b178dde6dcc2ef5799fc307b0a0e6d02751356/firmware/Core/Src/main.c#L114

**Checklist:**
 - In the device configurator set `ENC1_B` and `ENC2_B` as ordinary inputs. 
 - In `main.c` set the encoder resolution definitions to `EncoderResolution_1`
 - Set `MOTOR_ENCODER_MAX_SPEED_CPS` to 3000
 - Remove `encoderHandlerB()` calls
 - *Optional:* purge everything from `encoder.c` that's handling the higher resolutions

**Comment by dkiovics** [comment]
Encoder resolution reduced, timerOverflowCounter bug fixed
